from __future__ import annotations

from services.address import normalize_address, verify_address_input_service
from services.google import google_verify_address_from_lat_lng_service
from services.receipt import cross_reference_receipt_address_service